server:
  port: 80
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pc-web
  redis:  ##redis连接信息
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  main:
    allow-bean-definition-overriding: true