server:
  port: 8768
#  context-path: /pay
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: pay
  redis:  ##redis连接信息
    host: 127.0.0.1
    password: 123456
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  #数据库连接信息
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/shopping_pay
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

tm: 
  manager: 
    url: http://127.0.0.1:8899/tx/manager/
        
alipay: 
  #应用ID,您的APPID，收款账号既是您的APPID对应支付宝账号
  app_id: 2016100100640424
  #商户私钥，您的PKCS8格式RSA2私钥
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDASiRds4kX+sT63nJrqpiIUz6GQNUkAtvwZGyEkZx5y9UB8YTlQKW+9s6snitgTgFpU9DLf36BMoT5vBSHL0DSDWyWizElVf0HTI3oLPSfWmZNLVRMY2hvkxdXk/ErtGRehXUX1yI3PEAuGh086jIZBeyVJITrM7WRnZfMVsL5Ni31v2yCVEo1PvqJEG/fpwe5alDNqZ27jhPomjlJ6/GHTkQfgEGZJovk4qxltgnwrXxajUuV/0WRZVm5432WkMbRyZrxzWqDlYUpiHFS74BeFat+eN7GE4r7hfhDomwTeZexyIBKWlCr8E+CejgPp8ioSMHT7m2K6V8t4giNEd+7AgMBAAECggEAJXZMX3T64JEaj0WHRTKXRPfy1nULEVj9QHhQLAOyWIg9l4NWQNO3dtzepwKpsLmBzONnaj4Mh18wSPc7iJrMJiA3Z5z2li+KfEGN5A3eGq2iAKc0JS24ywP9KDLKaZlbdI7LoTlokRpL5q9vws5dtEJTNTtIKgqI9TWevVCp66MrVSqONyH4oMAaCi78kBBBgWSsnttIq0xY7SKQ9lOLT4+ieWKT5Sn71MzNb3kH8eXCvpz0eH/1S51GQHpvPJ3mqOcSVjO2h3thf7iLlQkJ8O65CSEO3nvJVMCR8/hiAlfDlL0vZNhhS8bzwut0qpw0JB4o5mfXxTERuzSRDvgJAQKBgQD9zjfMa35VkAyW/dJI8fiDUXUIPb41c5E4wdIQ7aQ8d0+ch7mZUAPkxlAw9bmMs4k7PuuZsQ4HkO493BQYkCcZfyzWWWJZ9fBx+AbAtV1svtHrPr9OMXJVvoVUoMpD6mCTbrWcrMmtFXQ0c1Vd2pIUI6viAiCvAjW+jHtne6XNJQKBgQDB88M6ClIcXsQjLWM61lOy46nvTvWFqbtT51p7RReN3MSMdvPx6jhyiEOFIt05AnsZPaSFMYZ1lt6ww32YiGUewA0k5AGWGnBIi3NZFcdZrYbrZlbrDlIiTNgVbgaNo8TZBhslqPU/agx50ZDPf9Bv3CVGYnhykDlDWg57yL0TXwKBgQDSp+WiMpoR9FSuwg9WYhetDt//LhgAj2I6ZIyxZjzJvxGBzxkaCdKhgIQwjtMp2B4P4YJ09wK4/u7uwwqe9I6vV+HkKx45oqqmPYGFU0MurhbXlSX9hYbrag2KF0aqJg9wbxQn7TYbBdKEcjGpi29xbcYM+U0dVM080abfVj5gTQKBgGDtYXNwFPj4oyyxUhXlZo7QF+zwmOLjoCqeRCm2rb7HxbItAFy1oOAcGSI/+i6zfrFujPnDdl7ttvy/tdS01VQ4xljZWbGaJOMcTdkHeUjn37Vkv6tYzNM3dAXBpqTCY23SD18SwP2gEfwPLz+DsLc2Xap/K5KVYQi3yOUzvMohAoGAT3hW16uzBJwr3v9539VJcwhUXvjGa0ALHNFNo44R3LRnjDtvJrml5MzSApQ1fcoCHjcQKEayKq2GkJkAzrTp0jt5D3a0r1QDyLd7pR1ZNHZf8fX0V7WFfeCK8bpYJDuGRjLI1xKETHK3/l0IVFaPLigfj+pv8ZSuBizmDZvjOe8=
  #支付宝公钥,查看地址：https://openhome.alipay.com/platform/keyManage.htm 对应APPID下的支付宝公钥。 
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyD7RgM1E+Q4YR9dKgYyaIRXA2RUzXkwGOjPMGPhsdnVITM9yVdqBclPAHv/R5UMTgo+AKM/57HYRMmhr8Kte8fxYEDs84v6y1J5W4qo8Z7p9rCZdEt/oBU70NLdBNlWITr0df3zW58nSm90wLTgXPqrXr2yQ28XGCih8Oqb92n8jbdJmyxQ3LObnj5YtKfHJ6hh+XzJWIIeT6aQW+ENiYvfbLUBW6tRKcm8WusORiM1KoghbeaahTru16FIPgdHl98rOPbHT3iJAGJzXRs0gvOKOJp+4lwpuOrMkHzm1KPHxiQOXTBPY73FMA1snTadwisVKO7YqDCXP0JJvRmuJ1QIDAQAB
  #服务器异步通知页面路径  需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  notify_url: http://2614f7r713.wicp.vip/alibaba/notifyUrl
  #页面跳转同步通知页面路径 需http://格式的完整路径，不能加?id=123这类自定义参数，必须外网可以正常访问
  return_url: http://2614f7r713.wicp.vip/alibaba/returnUrl
  #签名方式
  sign_type : RSA2
  #字符编码格式
  charset : utf-8
  #支付宝网关
  gatewayUrl : https://openapi.alipaydev.com/gateway.do
  log_path : C:\\
